version: '3.6'
services:
  postgres-user-profile:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin_123
      - POSTGRES_DB=clinzed
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - user_profile_api_data:/data/postgres
    ports:
      - 5432:5432
volumes:
  user_profile_api_data: {}
